#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Waton >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Waton=/luci-static/waton
		set luci.main.mediaurlbase=/luci-static/waton
		commit luci
	EOF
fi

exit 0
